SOR/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('carrello/', include('carrello.urls', namespace='carrello')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOR/login/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views

from .forms import SignIn
#per richiamare gli url --> namespace_app:nome_url
app_name = 'login'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name='users/login.html', form_class=SignIn), name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='/login/login/'), name='logout'),
     path('register/', views.user_registration, name='register'),
     path('invalid/', views.invalid_registration, name='invalid'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
     path('wishlist/', views.wishlist_content, name='wishlist'),
     path('add/', views.add_to_wishlist, name='add_to_wishlist'),    
     path('remove/', views.wishlist_remove, name='wishlist_remove'),
]

SOR/login/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.core.mail import send_mail
#from django.urls import reverse 
#from django_countries.fields import CountryField

class AccountManager(BaseUserManager):

    def create_superuser(self, email, username, password, **other):

        other.setdefault('is_staff', True)
        other.setdefault('is_superuser', True)
        other.setdefault('is_active', True) 
        return self.create_account(email, username, password, **other)
    

    def create_account(self, email, username, password, **other):

        if not email:
            raise ValueError(('Devi inserire un indirizzo email'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          **other)
        user.set_password(password)
        user.save()
        return user



class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(('email address'), unique=True)
    username = models.CharField(max_length=60, unique=True)
    
    # User Status
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    #created = models.DateTimeField(auto_now_add=True)
    #updated = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = "Accounts"
        verbose_name_plural = "Accounts"

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            'l@1.com',
            [self.email],
            fail_silently=False,
        )

    def __str__(self):
        return self.username

 

SOR/login/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm)

from .models import Account
#i field dei form di django risultano come campi di input nei file HTML

class SignIn(AuthenticationForm):

    username = forms.CharField(min_length=3, max_length=50, help_text='Required')
    password = forms.CharField( widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        

class Register(forms.ModelForm):
     username = forms.CharField(min_length=4, max_length=50, help_text='Required')
     email = forms.EmailField(max_length=100, help_text='Required', error_messages={'required': 'tentare con un altro indirizzo email'})
     password = forms.CharField(widget=forms.PasswordInput)
     password2 = forms.CharField( widget=forms.PasswordInput)

     class Meta:
          model = Account
          fields = ('username', 'email',)

     def check_if_valid_username(self):
          username = self.cleaned_data['username'].lower()
          r = Account.objects.filter(username=username)
          if r.count():
               raise forms.ValidationError("User già esiste")
          return username
     
     def clean_email(self):
        input = self.cleaned_data['email']
        if Account.objects.filter(email=input).exists():
            raise forms.ValidationError(
                'La mail utilizzata già esiste per un altro account')
        return input
     
     def clean_password2(self):
        password = self.cleaned_data
        if password['password'] != password['password2']:
            raise forms.ValidationError('Le password non corrispondono')
        return password['password2']
     
     
     def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})


     

SOR/login/views.py
from django.shortcuts import render
from .forms import Register
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.shortcuts import get_object_or_404
from .tokens import account_activation_token
from .wishlist import Wishlist
from store.models import Product
from .models import Account

def add_to_wishlist(request):
    print(request)

    wishlist = Wishlist(request)
    if request.POST.get('action') == 'post':
        productID = int(request.POST.get('productID'))
        product_amount = int(request.POST.get('amount'))
        product = get_object_or_404(Product, id=productID)
        wishlist.insert(product=product, amount=product_amount)

        total = 0 #wishlist.__len__()
        
        response = JsonResponse({'amount': total})
        return response
    

def wishlist_content(request):
    wishlist = Wishlist(request)
    return render(request, 'users/.html')

def wishlist_remove(request):
    print(request)
    wishlist = Wishlist(request)
    if request.POST.get('action') == 'post':
        id = int(request.POST.get('productID'))
        wishlist.removeItem(item=id)
        
        number = wishlist.__len__()
        total = wishlist.get_tot()
        response = JsonResponse({'qty': number, 'subtotal': total})
        #response = JsonResponse({'success': True})
        return response


# Create your views here.
def user_registration(request):

    if request.user.is_authenticated:
        return redirect('login:dashboard')
    
    if request.method == 'POST':
        registerForm = Register(request.POST)
        if registerForm.is_valid():
            costumer = registerForm.save(commit=False)
            costumer.email = registerForm.cleaned_data['email']
            costumer.set_password(registerForm.cleaned_data['password'])
            costumer.is_active = False
            costumer.save()
            sito_web = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('users/email.html', {
                'user': costumer,
                'domain': sito_web.domain,
                'uid': urlsafe_base64_encode(force_bytes(costumer.pk)), #user identifier
                'token': account_activation_token.make_token(costumer),
            })
            costumer.email_user(subject=subject, message=message)
            return HttpResponse('è stata inviata una mail di verifica')
        else:
            return redirect('login:invalid')
            # return HttpResponse(' NOT registered USER ')
    else:
        subscription = Register()
        return render(request, 'users/subscribe.html', {'form': subscription})
    
@login_required
def dashboard(request):
    return render(request,
                  'users/accountPage.html')

def invalid_registration(request):
    return render(request,
                  'users/invalidRegistration.html')

def account_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        pass
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('login:dashboard')
    else:
        return HttpResponse('registered grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr GOOD USER ')
 

SOR/templates/users/accountPage.html
{% extends "store/base.html" %} {% load static %} {% block title %}dashboard{%endblock %} 

{% block content %}
<div class="container">
    <div class="col-12">
      <h1 class="h2 text-white">Dashboard</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
      <div class ="text-white">Ciao {{ user.username }}, <br>Benvenuto nel tuo <b>account</b>, questa è la tua pagina personale di riferimento</div>
      <div class ="text-white"><a href="/">Inizia lo shopping!</a></div>
    </div>
    <hr />
  </div>

  <div class="album py-5 bg-info text-dark">

    <main class="pt-5">
        <div class="container">
         
          <h1 class="h7">Wishlist                                                                               
            
          </h1>
            {% for item in wishlist %}
            {% with product=item.product %}
            <div data-index="{{product.id}}" class="row mb-4 product-item">
              <div class="col-md-3 col-lg-2 order-md-first bg-info">
                <img class="img-fluid mx-auto d-block border border-danger" alt="Responsive image" src="{{ product.cover.url }}">
              </div>
              <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                  <h1 class="h5 pt-2">{{ product.title }}
                     <a href="{{ product.artist.get_absolute_url }}" class="text-secondary">
                            {{ product.artist }}
                     </a>
                 </h1>
                  
                </a>
                
                <div class="border bg-secondary">
                  
                  <div class="col">
                    <div class="row p-3">
                      <div class="col-12">
                         ${{ product.price }}
                        <button type="button" id="delete-button" data-index="{{product.id}}"
                          class="btn btn-outline-secondary btn-sm delete-button bg-danger text-white">
                          Delete
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
            </div>
            
        </main>
    </div>
    
        <script>
          $(document).on('click', '#delete-button', function (e) {
            e.preventDefault(); 
            var prodid = $(this).data('index');     
            $.ajax({
                type: 'POST',
                url: '{% url "login:wishlist_remove" %}',
                data: {
                    productID: $(this).data('index'),             
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                  $('.product-item[data-index="' + prodid + '"]').remove();
                  document.getElementById("subtotal").innerHTML = json.subtotal;
                  document.getElementById("qty").innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {}
            });
        })
        </script>
    

{%endblock %} 

SOR/templates/users/email.html
{% autoescape off %}
Ciao {{ user.username }},

Account creato con successo. Clicca sul link qui sotto per attivare l'account

http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}
{% endautoescape %}

SOR/templates/users/invalidRegistration.html
{% extends "store/base.html" %} {% load static %} {% block title %}invalid{%endblock %} 

{% block content %}
<div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2 text-white">Registrazione non valida</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
      <div class ="text-white">riprova a registrarti cliccando sull'icona <b>account</b> e inserisci con attenzione i tuoi dati</div>
      <div class ="text-white"><a href="{% url 'login:register' %}">Riprova</a></div>
    </div>
    <hr />
  </div>
  
{% endblock %}

SOR/templates/users/login.html
{% extends "store/base.html" %}
{% block title %}register{% endblock %}
{% block content %}



<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <form class="account-form p-4 rounded" action="{% url 'login:login' %}" method="post">

                                {% csrf_token %}
                                <h3 class="mb-4">Sign In</h3>

                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Username or Password not correct!
                                </div>
                                {% endif %}

                                <label class="form-label text-white">{{ form.username.label}}</label>
                                {{ form.username}}

                                <label class="form-label text-white">{{ form.password.label}}</label>
                                {{ form.password}}
                                <div class="d-grid gap-2">
                                    <input type="hidden" name="next" value="{{ next }}">
                                    <button class="btn btn-primary py-2 mb-4 mt-5 fw-bold" type="submit" value="Log-in">Sign in
                                    </button>
                                </div>
                                <p class="text-center pb-3">
                                    <a href="{% url "login:register" %}">Create an account</a>
                                </p>
                            </form>
                            <p class="small text-center pt-4">
                                {% comment %} <a href="{% url "password_reset" %}">Forgotten Password?</a> {% endcomment %}
                            </p>
                            <p class="small text-center">
                                {% comment %} <a href="{% url "accounts:register" %}">Help Center?</a> {% endcomment %}
                            </p>
                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

SOR/templates/users/subscribe.html
{% extends "store/base.html" %}
{% block title %}register{% endblock %}
{% block content %}
<div class="container-fluid">
    
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7  mx-auto">
                             <form class="account-form p-4 rounded col-lg-10 mx-auto" action="." method="post">
                                {% csrf_token %}
                                <h3 class="mb-2 font-weight-bold text-white">Crea un account</h3>
                                <p class="mb-4 text-white">è gratis, facile e veloce</p>

                                {% if form.errors %}
                                <p class="text-white">Correggi i seguenti errori:</p>
                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Errore: Username o Password non corretti!
                                </div>
                                {% endif %}
                                {% for field in form %}
                                {% if field.errors %}
                                <div class="alert alert-primary" role="alert">
                                    {{ field.label }}: {{ field.errors|striptags }}
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}

                                <label class="text-white">inserisci il tuo username<span class="text-muted small">
                                        (Campo Obbligatorio)</span></label>
                                {{ form.username }}
                                <label class="text-white">Email<span class="text-muted small">
                                        (Campo Obbligatorio)</span></label>
                                {{ form.email }}
                                <label  class="text-white">Password<span class="text-muted mb-4">
                                        </span></label>
                                 <small class="form-text text-muted mb-4 small">
                                    Consigliata con almeno 8 caratteri e 1 numero
                                </small>
                                {{ form.password }}
                                <label class="text-white">Ripeti la password<span class="text-muted small">
                                        (Campo Obbligatorio)</span></label>
                                {{ form.password2 }}
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Iscriviti</button>
                                <p class="text-center">
                                    <a href="{% url "login:login" %}">Hai già un account?</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
</div>

{% endblock %}

SOR/templates/users/wishlist.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Wishlist{% endblock %}
{% block content %}
  
<div class="album py-5 bg-dark text-white">

<main class="pt-5">
    <div class="container">
     
      <h1 class="h7">Wishlist                                                                               
        
      </h1>
        {% for item in wishlist %}
        {% with product=item.product %}
        <div data-index="{{product.id}}" class="row mb-4 product-item">
          <div class="col-md-3 col-lg-2 order-md-first bg-dark">
            <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ product.cover.url }}">
          </div>
          <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
              <h1 class="h5 pt-2">{{ product.title }}
                 <a href="{{ product.artist.get_absolute_url }}" class="text-secondary">
                        {{ product.artist }}
                 </a>
             </h1>
              
            </a>
            
            <div class="border bg-secondary">
              
              <div class="col">
                <div class="row p-3">
                  <div class="col-12">
                     ${{ product.price }}
                    <button type="button" id="delete-button" data-index="{{product.id}}"
                      class="btn btn-outline-secondary btn-sm delete-button bg-danger text-white">
                      Delete
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
        </div>
        
    </main>
</div>

    <script>
      $(document).on('click', '#delete-button', function (e) {
        e.preventDefault(); 
        var prodid = $(this).data('index');     
        $.ajax({
            type: 'POST',
            url: '{% url "login:wishlist_remove" %}',
            data: {
                productID: $(this).data('index'),             
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
              $('.product-item[data-index="' + prodid + '"]').remove();
              document.getElementById("subtotal").innerHTML = json.subtotal;
              document.getElementById("qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
    </script>

{% endblock %}