SOR/carrello/urls.py
from django.urls import path 
from . import views 

app_name = 'carrello'

urlpatterns = [
    path('', views.carrello_content, name='carrello_content'),
    path('add/', views.carrello_add, name='carrello_add'),    
    path('remove/', views.carrello_remove, name='carrello_remove'),
    #path('update/', views.carrello_update, name='carrello_update'),
]

SOR/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('carrello/', include('carrello.urls', namespace='carrello')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOR/login/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views

from .forms import SignIn
#per richiamare gli url --> namespace_app:nome_url
app_name = 'login'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name='users/login.html', form_class=SignIn), name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='/login/login/'), name='logout'),
     path('register/', views.user_registration, name='register'),
     path('invalid/', views.invalid_registration, name='invalid'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
     path('wishlist/', views.wishlist_content, name='wishlist'),
     path('add/', views.add_to_wishlist, name='add_to_wishlist'),    
     path('remove/', views.wishlist_remove, name='wishlist_remove'),
]

SOR/templates/products/artist.html
{% extends "store/base.html" %}

{% load static %}
{% block title %}Home{% endblock %} 

{% block content %}
<main>

  
    <div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-dark">
         
        <div class="pb-3 h1"><p class="badge badge-secondary bg-secondary">{{artist.name|title}}</p></div>

          <img class="img-fluid mx-auto d-block" width="500px" alt="Responsive image" src="{{ artist.picture.url }}">
        </div>

      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
          <h1 class="mb-0 h4"> <span class="text-white">Biografia</span></h1>
          <p><span class="lead text-white">bio</span></p> 
          <br>
          <p>
              <span class="text-white"> {{ artist.biography|linebreaksbr }}</p>
      </div>
    </div>
    </div>


    
<div class="album py-5 bg-dark">
      
  <div class="container">

    <div class="pb-3 h1"><p class="text-white bg-danger rounded"> <p class="badge badge-secondary bg-secondary">Album E Raccolte Disponibili</p></p></div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
  {% for product in products %}

  <div class="col">
    <div class="card shadow-sm">
      <img class="img-fluid" alt="Responsive image" src="{{ product.cover.url }}">
      <div class="card-body">
        <p class="card-text">
          <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted"> {{ product.artist }}</small>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}

</div>
</div>
</div>

  </div>



</main>




</div>




   
  
{% endblock %}

SOR/templates/products/category.html
{% extends "store/base.html" %}

{% load static %}
{% block title %}Home{% endblock %} 

{% block content %}
<main>

  
    <div class="album py-5 bg-dark">
      <div class="container">
        <h3 class="text-white">Genere  <span class="badge badge-secondary bg-secondary">{{genre.name|title}}</span></h3> <br>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for product in products %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.cover.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted"> {{ product.artist }}</small>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>
  
  
  </main>
  
{% endblock %}

SOR/templates/products/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-dark">
                
                <img class="img-fluid mx-auto d-block" width="500px" alt="Responsive image" src="{{ product.cover.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4"> <span class="text-white">{{ product.title }}</span></h1>
                <p><span class="lead text-white">{{ product.artist }}</span> (Artista)</p> 
                <p>
                    <span class="text-secondary"> {{ product.summary|linebreaksbr }}</span>...
                   </p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6 text-white">Vinile</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold text-white">€{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select"><p class="text-white">Quantità</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-danger btn-sm">Aggiungi al Carrello</button></div>
                                <button type="button" id="add-fav" value="{{product.id}}" class="btn btn-secondary fw500">Aggiungi alla Wishlist</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <p>
            <span class="text-white">{{ product.overview }}</p>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();        
        $.ajax({
            type: 'POST',
            url: '{% url "carrello:carrello_add" %}',
            data: {
                productID: $('#add-button').val(),
                amount: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                console.log(json)
                document.getElementById("amount").innerHTML = json.amount
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '#add-fav', function (e) {
        e.preventDefault();        
        $.ajax({
            type: 'POST',
            url: '{% url "login:add_to_wishlist" %}',
            data: {
                productID: $('#add-fav').val(),
                amount: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                console.log(json)
                document.getElementById("amount").innerHTML = json.amount
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}