SOR/carrello/urls.py
from django.urls import path 
from . import views 

app_name = 'carrello'

urlpatterns = [
    path('', views.carrello_content, name='carrello_content'),
    path('add/', views.carrello_add, name='carrello_add'),    
    path('remove/', views.carrello_remove, name='carrello_remove'),
    #path('update/', views.carrello_update, name='carrello_update'),
]

SOR/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('carrello/', include('carrello.urls', namespace='carrello')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOR/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    
    path('', views.all_products, name='all_products'),
    path('all', views.all_products_categories, name='all_products_categories'),
    path('artists', views.all_artists, name='all_artists'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:genre_slug>/', views.genre_list, name='genre_list'),

    path('<slug:artist_slug>', views.artist_list, name='artist_list'),
]

# <slug:slug> -> <tipoDiDato:nomeDato>

SOR/carrello/models.py
from django.db import models

# Create your models here.

SOR/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from django.conf import settings
#reverse -> permette di costruire un url
#templates dati a django per creare il database

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Genre(models.Model): #FIRST TABLE
    name = models.CharField(max_length=255, db_index=True) ##cercare documentazione!!!!!!!!!!!!
    slug = models.SlugField(max_length=255, unique=True)  
     #SLUGS ---> per mostrare categoria da mostrare nel sito, sono delle etichette che vanno negli urls 
    class Meta:
        verbose_name_plural = 'genres' #nome plurale per le categorie del database
    
    def get_absolute_url(self):
        return reverse('store:genre_list', args=[self.slug])

    def __str__(self):
        return self.name     
    


class Artist(models.Model): #FIRST TABLE
    name = models.CharField(max_length=255, db_index=True) 
    slug = models.SlugField(max_length=255, unique=True)  
    picture = models.ImageField(upload_to='images/')
    biography = models.TextField(blank=True)
    
     #SLUGS ---> per mostrare categoria da mostrare nel sito, come le directory nella shell
                  #no special characters, nome unico    
    class Meta:
        verbose_name_plural = 'artists' #nome plurale per le categorie
    
    def get_absolute_url(self):
        return reverse('store:artist_list', args=[self.slug])

    def __str__(self):
        return self.name     


class Product(models.Model):   
    genre = models.ForeignKey(Genre, related_name='product', on_delete=models.CASCADE) #related_name='product'
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin_creator')
    title = models.CharField(max_length=255)
    #artist = models.CharField(max_length=255, default='admin')
    artist = models.ForeignKey(Artist, related_name='product', on_delete=models.CASCADE) 
    summary = models.TextField(blank=True)
    overview = models.TextField(blank=True)
    cover = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)  
    price = models.DecimalField(max_digits=4, decimal_places=2)
    available = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products' #nome plurale per le categorie
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])  #per buildare secondo path in urls.py nella lista urlspatterns[]
                                        #product_detail=    name nella path in urls.py
  
    def __str__(self):
        return self.title  
    

SOR/carrello/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.http import Http404

from .carrello import Carrello
from store.models import Product
# Create your views here.

def carrello_content(request):
    #print(request)
    #print("carrello loaded from carrello_content")
    carrello = Carrello(request)
    return render(request, 'store/carrello/content.html')

def carrello_add(request):
    print(request)

    carrello = Carrello(request)
    if request.POST.get('action') == 'post':
        productID = int(request.POST.get('productID'))
        product_amount = int(request.POST.get('amount'))
        product = get_object_or_404(Product, id=productID)
        carrello.insert(product=product, amount=product_amount)

        total = carrello.__len__()
        
        response = JsonResponse({'amount': total})
        return response
    
def carrello_remove(request):
    print(request)
    carrello = Carrello(request)
    if request.POST.get('action') == 'post':
        id = int(request.POST.get('productID'))
        carrello.removeItem(item=id)
        
        basketqty = carrello.__len__()
        baskettotal = carrello.get_tot()
        round(baskettotal,2)
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        #response = JsonResponse({'success': True})
        return response

SOR/store/views.py
from django.shortcuts import get_object_or_404, render

#get_object_or_404 = shortcut per accedere ai dati del database

from .models import Genre, Artist, Product

def genres(request):
    return {
        'genres': Genre.objects.all()
    }

def artists(request):
    return {
        'artists': Artist.objects.all()
    }


def all_products_categories(request):
    products = Product.products.all()
    return render(request, 'store/allProducts.html', {'products': products})

def all_artists(request):
    artists = Artist.objects.order_by("name")
    return render(request, 'store/allArtists.html', {'artists': artists})

def all_products(request):
    products = Product.products.filter(pk__in=[1, 2, 3, 4, 5])  #sono gli album mostrati nella home
    return render(request, 'store/home.html', {'products': products})

def new_products(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    return render(request, 'products/detail.html', {'product': product})







def genre_list(request, genre_slug=None):
    genre = get_object_or_404(Genre, slug=genre_slug) 
    products = Product.objects.filter(genre=genre)
    return render(request, 'products/category.html', {'genre': genre, 'products': products})

def artist_list(request, artist_slug):
    artist = get_object_or_404(Artist, slug=artist_slug) 
    products = Product.objects.filter(artist=artist)
    return render(request, 'products/artist.html', {'artist': artist, 'products': products})

SOR/templates/store/carrello/content.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Carrello{% endblock %}
{% block content %}
  
<div class="album py-5 bg-dark text-white">

<main class="pt-5">
    <div class="container">
     
      <h1 class="h7">Carrello Prodotti                                                                                                  
        
      </h1>
        {% for item in carrello %}
        {% with product=item.product %}
        <div data-index="{{product.id}}" class="row mb-4 product-item">
          <div class="col-md-3 col-lg-2 order-md-first bg-dark">
            <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ product.cover.url }}">
          </div>
          <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
              <h1 class="h5 pt-2">{{ product.title }}</h1>
            </a>
            <div class="border">
              <div class="col border-bottom">
                <div class="row p-3">
                  <div class="col-6">Vinile</div>
                  <div class="col-6 text-end"><span class="h6 fw-bold">€ {{ product.price }}</span></div>
                </div>
              </div>
              <div class="col">
                <div class="row p-3">
                  <div class="col-12">
                    Quantità {{item.amount}}
                    
                    <button type="button" id="delete-button" data-index="{{product.id}}"
                      class="btn btn-outline-secondary btn-sm delete-button">
                      Delete
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
        {% endfor %}
        {% if carrello.get_tot == 0%} 
          Aggiungi qualcosa al tuo carrello!
          <br>
          <div class ="text-white"><a href="/">Inizia lo shopping!</a></div>
        {% else %}
        <div class="col-12 text-end text-bg-light">
            <div class="h6 fw-bold">Sub Total: € <div id="subtotal" class="d-inline-flex">{{carrello.get_tot}}</div></div>
            <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
          <div class="d-grid gap-2 ">
            <a role="button" href="#" class="btn btn-success fw-bold" type="button">Checkout</a>
           
          </div>
        </div>      
          </div>
        </div>
        {%endif%}
        
    </main>
</div>

    <script>
      $(document).on('click', '#delete-button', function (e) {
        e.preventDefault(); 
        var prodid = $(this).data('index');     
        $.ajax({
            type: 'POST',
            url: '{% url "carrello:carrello_remove" %}',
            data: {
                productID: $(this).data('index'),             
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
              $('.product-item[data-index="' + prodid + '"]').remove();
              document.getElementById("subtotal").innerHTML = json.subtotal;
              document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
    </script>

{% endblock %}