SOR/carrello/urls.py
from django.urls import path 
from . import views 

app_name = 'carrello'

urlpatterns = [
    path('', views.carrello_content, name='carrello_content'),
    path('add/', views.carrello_add, name='carrello_add'),    
    path('remove/', views.carrello_remove, name='carrello_remove'),
    #path('update/', views.carrello_update, name='carrello_update'),
]

SOR/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('carrello/', include('carrello.urls', namespace='carrello')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SOR/login/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views

from .forms import SignIn
#per richiamare gli url --> namespace_app:nome_url
app_name = 'login'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name='users/login.html', form_class=SignIn), name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='/login/login/'), name='logout'),
     path('register/', views.user_registration, name='register'),
     path('invalid/', views.invalid_registration, name='invalid'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
     path('wishlist/', views.wishlist_content, name='wishlist'),
     path('add/', views.add_to_wishlist, name='add_to_wishlist'),    
     path('remove/', views.wishlist_remove, name='wishlist_remove'),
]

SOR/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    
    path('', views.all_products, name='all_products'),
    path('all', views.all_products_categories, name='all_products_categories'),
    path('artists', views.all_artists, name='all_artists'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:genre_slug>/', views.genre_list, name='genre_list'),

    path('<slug:artist_slug>', views.artist_list, name='artist_list'),
]

# <slug:slug> -> <tipoDiDato:nomeDato>

SOR/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from django.conf import settings
#reverse -> permette di costruire un url
#templates dati a django per creare il database

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Genre(models.Model): #FIRST TABLE
    name = models.CharField(max_length=255, db_index=True) ##cercare documentazione!!!!!!!!!!!!
    slug = models.SlugField(max_length=255, unique=True)  
     #SLUGS ---> per mostrare categoria da mostrare nel sito, sono delle etichette che vanno negli urls 
    class Meta:
        verbose_name_plural = 'genres' #nome plurale per le categorie del database
    
    def get_absolute_url(self):
        return reverse('store:genre_list', args=[self.slug])

    def __str__(self):
        return self.name     
    


class Artist(models.Model): #FIRST TABLE
    name = models.CharField(max_length=255, db_index=True) 
    slug = models.SlugField(max_length=255, unique=True)  
    picture = models.ImageField(upload_to='images/')
    biography = models.TextField(blank=True)
    
     #SLUGS ---> per mostrare categoria da mostrare nel sito, come le directory nella shell
                  #no special characters, nome unico    
    class Meta:
        verbose_name_plural = 'artists' #nome plurale per le categorie
    
    def get_absolute_url(self):
        return reverse('store:artist_list', args=[self.slug])

    def __str__(self):
        return self.name     


class Product(models.Model):   
    genre = models.ForeignKey(Genre, related_name='product', on_delete=models.CASCADE) #related_name='product'
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin_creator')
    title = models.CharField(max_length=255)
    #artist = models.CharField(max_length=255, default='admin')
    artist = models.ForeignKey(Artist, related_name='product', on_delete=models.CASCADE) 
    summary = models.TextField(blank=True)
    overview = models.TextField(blank=True)
    cover = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)  
    price = models.DecimalField(max_digits=4, decimal_places=2)
    available = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products' #nome plurale per le categorie
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])  #per buildare secondo path in urls.py nella lista urlspatterns[]
                                        #product_detail=    name nella path in urls.py
  
    def __str__(self):
        return self.title  
    

SOR/store/views.py
from django.shortcuts import get_object_or_404, render

#get_object_or_404 = shortcut per accedere ai dati del database

from .models import Genre, Artist, Product

def genres(request):
    return {
        'genres': Genre.objects.all()
    }

def artists(request):
    return {
        'artists': Artist.objects.all()
    }


def all_products_categories(request):
    products = Product.products.all()
    return render(request, 'store/allProducts.html', {'products': products})

def all_artists(request):
    artists = Artist.objects.order_by("name")
    return render(request, 'store/allArtists.html', {'artists': artists})

def all_products(request):
    products = Product.products.filter(pk__in=[1, 2, 3, 4, 5])  #sono gli album mostrati nella home
    return render(request, 'store/home.html', {'products': products})

def new_products(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, available=True)
    return render(request, 'products/detail.html', {'product': product})







def genre_list(request, genre_slug=None):
    genre = get_object_or_404(Genre, slug=genre_slug) 
    products = Product.objects.filter(genre=genre)
    return render(request, 'products/category.html', {'genre': genre, 'products': products})

def artist_list(request, artist_slug):
    artist = get_object_or_404(Artist, slug=artist_slug) 
    products = Product.objects.filter(artist=artist)
    return render(request, 'products/artist.html', {'artist': artist, 'products': products})

SOR/templates/store/allArtists.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Home{% endblock %}  
<div class="p-4 p-md-5 mb-4 rounded text-bg-light">
{% block content %}
<main>

    <div class="album py-5 bg-dark">
      
      <div class="container">
  
        <div class="pb-3 h1"><p class="badge badge-secondary bg-secondary">Tutti Gli Artisti</p></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for artist in artists %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ artist.picture.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ artist.get_absolute_url }}">{{ artist.name }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">disponibile</small>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>

  </main>
  
{% endblock %}

SOR/templates/store/allProducts.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Home{% endblock %}  
<div class="p-4 p-md-5 mb-4 rounded text-bg-light">
{% block content %}
<main>

    <div class="album py-5 bg-dark">
      
      <div class="container">
  
        <div class="pb-3 h1"><p class="badge badge-secondary bg-secondary">Tutti I Prodotti</p></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for product in products %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.cover.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted"> {{ product.artist }}</small>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>

  </main>
  
{% endblock %}

SOR/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body class="bg-dark">
    
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-danger border-bottom">
            <div class="container-fluid">
                
                <img class="navbar-brand" href="/" src="https://erlych.altervista.org/wp-content/uploads/2021/07/ERLYCH-1.png"  height="90px" width="200px" alt="logo">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="{% url "store:all_artists" %}">Artists</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Genres
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:all_products_categories" %}">All</a></li>
                                {% for c in genres %}
                                <li {% if genre.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    
                </div>
                
                {% if user.is_authenticated %}
                <a type="button" role="button" href="{% url "login:logout" %}"
                    class="btn btn-outline-light border-0 basket-btn">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-door-closed" viewBox="0 0 16 16">
                            <path
                                d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                            <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                        </svg>
                    </div>
                    <span class="fs15 fw500">Logout</span>
                </a>
                {% else %}
                <a type="button" role="button" href="{% url "login:login" %}"
                    class="btn btn-outline-light border-0 basket-btn">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-door-closed" viewBox="0 0 16 16">
                            <path
                                d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                            <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                        </svg>
                    </div>
                    <span class="fs15 fw500">Login</span>
                </a>
                {% endif %}


                <a type="button" role="button" href="{% url "login:register" %}"
                class="btn btn-outline-light border-0 basket-btn">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                        class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                    </svg>
                </div>
                <span class="fs15 fw500">Account</span>
            </a>


                <a type="button" role="button" href="{% url "carrello:carrello_content" %}" class="btn btn-outline-light">
                    
                    {% with count=carrello|length %}
                    <div id="amount" class="d-inline-flex">
                        {% if count > 0 %}
                            {{ count }}
                        {% else %}
                            0
                        {% endif %}
                    </div>
                {% endwith %} 
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-cart2" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                    </svg>
                    Cart
                 </a>
            </div>
        </nav>
    </header>
    <div id="content" class="bg-dark"> <div class="p-4 p-md-5 mb-4 rounded bg-dark"> {% block content %} {% endblock %}</div>
</body>
</html>

SOR/templates/store/home.html
{% extends "./base.html" %}

{% load static %}
{% block title %}Home{% endblock %}  
<div class="p-4 p-md-5 mb-4 rounded text-bg-light">
{% block content %}
<main>

  
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner center">
      <ol class="carousel-indicators">
        <li data-target="carouselExampleSlidesOnly" data-slide-to="0" class="active"></li>
        <li data-target="carouselExampleSlidesOnly" data-slide-to="1"></li>
        <li data-target="carouselExampleSlidesOnly" data-slide-to="2"></li>
      </ol>
      <div class="carousel-item active">
        <div class="d-flex justify-content-center">
          <img src="https://www.pcprofessionale.it/wp-content/uploads/2017/12/digitalizzare-vinile-ape.jpg" class="d-block w-75" alt="..."> </div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center">
        <img src="https://images.wallpapersden.com/image/download/music-all-day-hd-scifi_bG1sZmWUmZqaraWkpJRmZWdprWpsaw.jpg" class="d-block w-75" alt="..."></div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center">
        <img src="https://collart.app/wp-content/uploads/sites/8/2021/12/collart_website_function_08_banner-maker02-template-pro-1024x576.jpg" class="d-block w-75" alt="..."></div>
      </div>
    </div>
    
  </div>

  <main class="container">
  <div class="p-4 p-md-5 mb-4 rounded text-bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic"><p class="text-white">Il negozio di dischi online più bello del mondo! </p></h1>
      <p class="lead my-3 text-white">Siamo un piccolo negozio di musica indipendente soltanto per veri intenditori!
        Compra e pre-ordina tutti i dischi, vinili e box set dei tuoi artisti preferiti! Inizia lo shopping adesso!</p>
      
    </div>
  </div>
  
  </main>
  
    <div class="album py-5 bg-danger rounded">
      
      <div class="container">
  
        <h3 class="text-white">What's  <span class="badge badge-secondary bg-dark">New</span></h3> <br>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for product in products %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.cover.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted"> {{ product.artist }}</small>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>

  </main>
  
  <script language="JavaScript" type="text/javascript">
    $(document).ready(function(){
      $('.carousel').carousel({
        interval: 2000
      })
    });    
  </script>
{% endblock %}